linters:
  enable-all: true
  disable:
    - unused
    - interfacer
    - ireturn
    - varnamelen
    - maligned
    - goerr113
    - paralleltest
    - testpackage
    - scopelint # deprecated
    - golint # deprecated
    - exhaustivestruct # deprecated
#  enable:
#    - bodyclose
#    - deadcode
#    - depguard
#    - dogsled
#    - dupl
#    - errcheck
#    - exportloopref
#    - exhaustive
#    - funlen
#    - gochecknoinits
#    - goconst
#    - gocritic
#    - gocyclo
#    - gofmt
#    - goimports
#    - gomnd
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - govet
#    - ineffassign
#    - lll
#    - misspell
#    - nakedret
#    - noctx
#    - nolintlint
#    - rowserrcheck
#    - staticcheck
#    - structcheck
#    - stylecheck
#    - typecheck
#    - unconvert
#    - unparam
#    - unused
#    - varcheck
#    - whitespace
#    - wsl
#    - revive
#    - exportloopref
#    - asciicheck
#    - gochecknoglobals
#    - goerr113
#    - gocognit
#    - godox
#    - godot
#    - nestif
#    - prealloc
#    - testpackage
#    - nestif
linters-settings:
  gci:
    sections:
      - Standard
      - Default
      - "Prefix(github.com/vasilesk)"
  funlen:
    lines: 80